### ISSUE TITLE
meta: API v2 roadmap

### ISSUE THREAD

**Issue by cyyynthia** [cyyynthia/pronoundb.org#68]
### API v1 is now **deprecated** and scheduled for removal on **June 1st, 2024**.

---

 - [x] Change internal representation of pronouns
   - Drop multiple sets as identifiers (e.g. `she/it`) and only keep individual sets
   - Represent multiple sets as arrays (`she/it` is currently `si`, would become `[ 'she', 'it' ]`
   - This change would allow solving the following issues:
     - #67 
     - #26 
 - [x] Unify `lookup` and `lookup-bulk` endpoints
   - This will simplify the internal logic and allow easier adoption of a bulk-based lookup model to lower stress on the PDB API
 - [x] Use standard JWT for authentication with expiry
   - Allow the use of "expired" tokens for fetching own pronouns, to let the extension show the currently-in-use pronouns?
 - [ ] Implement per-route rate limiting
 - [x] Allow for localized pronoun sets
   - Use query parameter, or browser headers, or fallback to English for the response, in that order of priority
 - [x] Future-proof data models for maybe :eyes: some new features

**Comment by ShadiestGoat** [comment]
> Represent multiple sets as arrays (she/it is currently si, would become [ 'she', 'it' ]

I'm not sure how far along you are in this, however, it might be cool to represent it as a double list. That way, people would be able to to put certain preferences above others. 
For example, `[ [ 'she', 'they' ], [ 'he' ] ]`  would represent that this person is ok with being referred to as 'she' or 'they' or 'he', but prefers the use of 'she'/'they' over 'he'. In this example 'she'/'they' are on equal preference. It would also mean that 'it' pronouns should not be applied to this person.

**Comment by cyyynthia** [comment]
I don't like this approach all that much. It makes the data structure quite complex to deal with (from a tuple of 1-3 elements to a tuple of 1-3 tuples of 1-3 elements) and makes it hard to consume.

I've been thinking about adding dedicated fields regarding preferences, which would cover this use case but also allow fields for languages like French where words have a masculine/feminine form which form to use when the person is only using neutral pronouns.

There ideas are still drafts and won't make it to the initial release of API v2. For now, this level of "detail" isn't the priority

**Comment by ShadiestGoat** [comment]
Is there a branch for this?

**Comment by cyyynthia** [comment]
Nope. I haven't really started working on large scale APIv2 work and instead have just been drafting things for now, without real-world code. If anything, the very recent full-blown rewrite in #83 would've ruined any prior work towards APIv2 😅

**Comment by cyyynthia** [comment]
I've started drafting and laying down what I need/want for APIv2. While it's theoretically possible to add all I want without breaking things, I really want to get rid of the legacy way of representing pronouns, so I'll still make it a fully fledged v2.

lookup and lookup-bulk will be merged into a single API endpoint, as announced, and the result will be of the following format:
```json
{
	"decoration": "string or null",
	"sets": {
		"en": [ "set1", "set2", "set3" ]
	}
}
```

 - `sets` is a map of locales to pronouns sets (1 to 3). At the initial v2 release, only `en` locale will be supported.
 - APIv2 supports up to 3 sets instead of the current 2 sets. However, in some places (e.g. Twitch chats) only the first two will be displayed
 - APIv2 will support things such as `she/any`, `they/ask`, `he/other`. No additional set can be added after "any" or "ask" or "other".
 - `avoid` can only be a single set, such as currently
 - APIv1 will use the following algorithm to determine the legacy set mapping: considering `sets` an array of sets:
   - if  `sets[0]` is `avoid`, then return `avoid`
   - if `sets` contain `any`, return `any`
   - if `sets` contain `ask`, return `ask`
   - if `sets[0]` is a legacy set, then:
     - if `sets[1]` is a legacy set, then return the legacy combined set
     - else, return only legacy `sets[0]`
   - else, return `other`
 - `decoration` is related to an upcoming feature I won't say much about for now :p

**Comment by cyyynthia** [comment]
Progress update: the pronouns picker got a big upgrade as well, and now everything behind the scenes uses the new pronouns representation. 🎉 

Here is a preview of the revised pronouns picker, including a video of it in action (shows the input being "forced" to be valid, as well as the handling of "final" sets such as "any", "ask", or "other":

![image](https://github.com/cyyynthia/pronoundb.org/assets/9999055/2b093784-3c2a-41ea-83ca-0bfc4d8fb4bc)

https://github.com/cyyynthia/pronoundb.org/assets/9999055/6ba953ec-2408-430a-8238-89f933eb2e0b

Note that the pronoun picker is gradually enhanced, and users who do not have JavaScript enabled can still fill out the form using a basic UI without the fancy stuff.

![image](https://github.com/cyyynthia/pronoundb.org/assets/9999055/0f7a3f42-5c0a-4fae-bbf9-f6c55aec73fe)

---

Remains to do, the implementation of APIv2 endpoints, which should now be relatively straightforward, and prepare the database migration from legacy format to new format.

Also remains to do porting the extension to the new APIv2; however as a portion of the pronouns formatting work has been moved to a shared package, a fair bit of the work has already been done. 🎉

**Comment by cyyynthia** [comment]
APIv2 is now live! See the new docs here: https://pronoundb.org/wiki/api-docs

APIv1 will continue operating for now, and is scheduled for removal on June 1st, 2024.

**Comment by NoPlagiarism** [comment]
Issue could unpinned already?
